# Generated by Django 4.0.6 on 2022-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('article_image', models.ImageField(null=True, upload_to='article/', verbose_name='Изборажение')),
                ('big_status', models.BooleanField(default=False, verbose_name='Большая статья')),
                ('preview_image', models.ImageField(upload_to='article/', verbose_name='Предварительное изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['date', 'title'],
            },
        ),
    ]
