# Generated by Django 4.0.6 on 2022-08-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=True, upload_to='article/<django.db.models.fields.CharField>', verbose_name='Изборажение'),
        ),
    ]
