# Generated by Django 4.0.6 on 2022-08-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date', 'title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
