# Generated by Django 4.0.6 on 2023-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(max_length=200, verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('more_info', models.TextField(blank=True, max_length=650, verbose_name='Подробнее')),
                ('money_limit', models.CharField(max_length=127, verbose_name='Лимит по займу')),
                ('age_start', models.CharField(default=18, max_length=127, verbose_name='Начальный возраст')),
                ('age_end', models.CharField(default=65, max_length=127, verbose_name='Конечный возраст')),
                ('stake', models.FloatField(blank=True, null=True, verbose_name='Процентная ставка')),
                ('text_left_from_stake', models.CharField(blank=True, max_length=100, verbose_name='Текст слева от процентной ставки')),
                ('text_right_from_stake', models.CharField(blank=True, max_length=100, verbose_name='Текст слева от процентной ставки')),
                ('url', models.URLField(max_length=250, null=True, verbose_name='Ссылка')),
                ('display', models.BooleanField(default=True, verbose_name='Отображение на странице')),
                ('filter_status', models.BooleanField(default=False, verbose_name='Отображение после формы')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['id', 'display', 'title'],
            },
        ),
    ]
