<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-11-18 07:58
=======
# Generated by Django 4.0.6 on 2022-11-18 11:48
>>>>>>> e868cd27a4390496e4f92b0d1662d7b48fc62229

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='more_info',
<<<<<<< HEAD
            field=models.TextField(blank=True, max_length=600, verbose_name='Подробнее'),
=======
            field=models.TextField(blank=True, max_length=650, verbose_name='Подробнее'),
>>>>>>> e868cd27a4390496e4f92b0d1662d7b48fc62229
        ),
    ]
