# Generated by Django 4.0.6 on 2022-08-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/<django.db.models.fields.CharField>/')),
                ('more_info', models.TextField(blank=True, max_length=255, verbose_name='Подробнее')),
                ('money_limit', models.IntegerField(verbose_name='Лимит по займу')),
                ('display', models.BooleanField(default=True, verbose_name='Отображение на странице')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['display', 'title'],
            },
        ),
    ]
