# Generated by Django 4.0.6 on 2022-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='more_info',
            field=models.TextField(blank=True, max_length=400, verbose_name='Подробнее'),
        ),
    ]
