# Generated by Django 4.0.6 on 2022-08-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='age_end',
            field=models.PositiveSmallIntegerField(default=65, verbose_name='Конечный возраст'),
        ),
        migrations.AddField(
            model_name='services',
            name='age_start',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Начальный возраст'),
        ),
        migrations.AddField(
            model_name='services',
            name='stake',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процентная ставка'),
        ),
        migrations.AddField(
            model_name='services',
            name='text_left_from_stake',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст слева от процентной ставки'),
        ),
        migrations.AddField(
            model_name='services',
            name='text_right_from_stake',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст слева от процентной ставки'),
        ),
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.URLField(max_length=250, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='services',
            name='money_limit',
            field=models.PositiveSmallIntegerField(verbose_name='Лимит по займу'),
        ),
    ]
