# Generated by Django 4.0.6 on 2022-08-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_services_age_end_services_age_start_services_stake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='stake',
            field=models.FloatField(blank=True, null=True, verbose_name='Процентная ставка'),
        ),
    ]
