# Generated by Django 4.0.6 on 2022-08-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_services_stake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id', 'display', 'title'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
    ]
