# Generated by Django 4.0.6 on 2022-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='filter_status',
            field=models.BooleanField(default=False, verbose_name='Отображение после формы'),
        ),
    ]
